
/**************************************************************
 *	
 *	bubble, 8 bit, 11025Hz,
 *	1 channel, 1734 bytes/channel
 *	Total Size: 1 * 1734 + 4 (header) = 1778 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\jlee9\Desktop\final-project-glee3491\bubble.wav
 *	Time-stamp: Thu Apr 23 05:25:36 2020
 *	
 **************************************************************/

#ifndef __BUBBLEH__
#define __BUBBLEH__

#define BUBBLEFREQ 11025
#define BUBBLELEN 1734

extern const unsigned char bubble[1734];

#endif /* __BUBBLEH__ */
