
/**************************************************************
 *	
 *	huffnpuff, 8 bit, 11025Hz,
 *	1 channel, 1965888 bytes/channel
 *	Total Size: 1 * 1965888 + 4 (header) = 1965932 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\jlee9\Desktop\final-project-glee3491\huffnpuff.wav
 *	Time-stamp: Thu Apr 23 05:14:33 2020
 *	
 **************************************************************/

#ifndef __HUFFNPUFFH__
#define __HUFFNPUFFH__

#define HUFFNPUFFFREQ 11025
#define HUFFNPUFFLEN 1965888

extern const unsigned char huffnpuff[1965888];

#endif /* __HUFFNPUFFH__ */
